FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy necessary files into the container
COPY requirements.txt /app
COPY .env /app
COPY streamlit_GCP.sh /app
COPY code /app/code

# Install the dependencies
RUN pip install -r requirements.txt

# Give execute permissions
RUN chmod +x streamlit_GCP.sh

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Run Shell startup script
CMD ["/app/streamlit_GCP.sh"]
